### ISSUE TITLE
Nek5000 Example

### ISSUE THREAD

**Issue by mmrezaie** [Kitware/ParaViewCatalystExampleCode#7]
I am trying to learn to implement an in-situ example for Nek5000 simulation. Is there one? I do not mind to share my code in here. 

I do have a running example by using VISIT/Libsim but my visualization code is being implemented in ParaView so if I port my In-situ from VISIT to here makes sense, but I am not sure how and even if it is possible?!

**Comment by acbauer** [comment]
It should be possible to use ParaView Catalyst with Nek5000 but the in situ API is a bit different than Libsim's API. Note that this repository is not active any more since the Catalyst examples are actively maintained in the main ParaView repo at https://gitlab.kitware.com/paraview/paraview. The examples are under the Examples/Catalyst subdirectory of that repo. The main Catalyst web page is at https://www.paraview.org/in-situ/ and the users guide is at https://www.paraview.org/files/catalyst/docs/ParaViewCatalystUsersGuide_v2.pdf. The best way to get help on Catalyst questions is through the paraview@paraview.org mailing list.

**Comment by mmrezaie** [comment]
Thanks. But is there an example for Nek5000 somewhere being presented or done before?
